apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  ttlSecondsAfterFinished: 5
  template:
    spec:
      containers:
      - name: myapp
        image: ekaterinakrotova/java-app:$(BUILD_NUMBER)
      restartPolicy: Never