version: '3.9'

services:
  app:
    build:
      context: ../apps/backend/src/
      dockerfile: ../Dockerfile
    image: yourusername/backend:1.0.0
    environment:
      APP_HOST: 0.0.0.0
    networks:
      - mynetwork

  nginx:
    image: nginx:stable
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
