version: '3.9'

services:
  backend:
    build:
      context: backend-app/src
      dockerfile: ../Dockerfile
    image: zava2012/backend:1.0.0
    restart: always
    container_name: backend-app
    # labels:
    #   com.centurylinklabs.watchtower.enable: true
    environment:
      APP_HOST: 0.0.0.0
    ports: ["5000"]
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports: ["5432"]

  frontend:
    build: frontend-app/
    image: zava2012/frontend:1.0.0
    restart: always
    # container_name: frontend-app
    environment:
      REACT_APP_NAME: myenv
    ports:
      - 80:80

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      WATCHTOWER_DEBUG: "true"
      WATCHTOWER_POLL_INTERVAL: 60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
