version: '3.9'

services:
  backend:
    build:
      context: backend-app/src
      dockerfile: ../Dockerfile
    image: backend:1.0.1
    restart: always
    # container_name: backend-app
    environment:
      APP_HOST: 0.0.0.0
    ports: ["5000"]
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports: ["5432"]

  frontend:
    build: frontend-app/
    image: frontend:1.0.1
    restart: always
    # container_name: frontend-app
    environment:
      REACT_APP_NAME: myenv
    ports:
      - 80:80
