version: '3.9'

x-common: &common
  restart: always
  networks:
    - common-network
  logging:
    driver: json-file
    options:
      max-size: "50"

x-asdasd: &asddsfghju
  networks:
    - common-network2

services:
  backend:
    build:
      context: backend/src
      dockerfile: ../Dockerfile
      # args:
      #   APP_HOST: 0.0.0.0
    image: yourusername/backend:${MY_TAG}
    # entrypoint: python3
    # command: app.py
    # container_name: backend
    labels:
      com.centurylinklabs.watchtower.enable: false
    <<: *asddsfghju
    <<: *common
    environment:
      APP_HOST: ${MY_APP_HOST}
      &myobjectasd HOST_PATH: asdasd
      HOST_PATH: &myenvasd asdasd
      MY_NESTED_OBJECT: *myobjectasd
      MY_NESTED_PATH: *myenvasd
    volumes:
      - ./myvolume:/data
    ports: ["${PORT}"]
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    <<: *common
    ports: ["5432"]

  frontend:
    build: frontend/
    image: yourusername/frontend:1.0.0
    restart: always
    # container_name: frontend
    environment:
      REACT_APP_NAME: myenv
    <<: *common
    ports:
      - 80:80

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      WATCHTOWER_DEBUG: "true"
      WATCHTOWER_POLL_INTERVAL: 60
    <<: *common
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


volumes:
  postgres:
    external: true

networks:
  common-network2:
    external: true
  common-network:
