pipeline{
    agent{
        label 'docker'
    }
    environment{
        IMAGE_REPO = 'ekaterinakrotova/java-app'
        TAG = '1.0.0'
    }
    stages {
        stage("Build App") 
        {
        steps {
            sh 'docker build -t $IMAGE_REPO:$TAG-$GIT_COMMIT -t $IMAGE_REPO:latest ./ci_cd/krotova_dz/2_homework/'
        }
    }
    }
}