{{- if .Values.envSecrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devopsschool.fullname" . }}
  {{- if .Values.secret.annotations }}
  annotations:
  {{- range $key, $value := .Values.secret.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
stringData:
{{- range $key, $value := .Values.envSecrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
type: Opaque
{{- end }}


{{ if .Values.secretFiles -}}
{{ range .Values.secretFiles -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "devopsschool.fullname" $ }}-{{ .name }}"
  {{- if $.Values.secret.annotations }}
  annotations:
  {{- range $key, $value := $.Values.secret.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
stringData:
{{- range $key, $value := .data }}
{{ $key | indent 2 }}: |
{{ toYaml $value | indent 4 }}
{{- end }}
type: {{ .type }}
{{ end }}
{{ end }}
