apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myappingress
spec:
  rules:
  - host: <mydomain>
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: nginxservice
            port:
              number: 80
      - pathType: Prefix
        path: /api
        backend:
          service:
            name: nginxnextservice
            port:
              number: 80
